[target.'cfg(target_arch = "aarch64")']
rustflags = ["-C", "target-feature=+neon", "--cfg", "chacha20_force_neon"]

[target.'cfg(target_arch = "x86_64")']
rustflags = [
    "-C", "target-cpu=sandybridge",
    "-C", "target-feature=+aes,+sse2,+sse4.1,+ssse3"
]
